apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "pg.migrator.secret.name" . }}
  labels:
  {{- include "pgSchema.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.database.postgres.username | b64enc | quote}}
  password: {{ .Values.database.postgres.password | b64enc | quote}}