apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "app.secret.name" . }}
  labels:
  {{- include "app.labels" . | nindent 4 }}
type: Opaque
stringData: 
  secrets.yaml: |-
    database:
      postgres:
        user: {{ .Values.database.postgres.username }}
        password: {{ .Values.database.postgres.password }}