apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "app.service.name" . }}
  labels:
  {{- include "app.labels" . | nindent 4 }}
spec:
  selector:
  {{- include "app.labels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: {{ .Values.simpleMs.port }}
    targetPort: {{ include "app.pod.exposedPort" . }}
  type: ClusterIP
