apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-ingress
  labels:
  {{- include "app.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1/
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.simpleMs.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path:  {{ .Values.simpleMs.ingress.urlPrefix }}/(.*[^/])
        backend:
          service:
            name: {{ include "app.service.name" . }}
            port: 
              number: {{ .Values.simpleMs.port }}
